version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_app
    image: ecommerce_img/ecommerce_img
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    env_file:
      - .env
