# Generated by Django 5.1.7 on 2025-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
