# Generated by Django 5.1.7 on 2025-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_produit_active_alter_produit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, default='pase de description', null=True),
        ),
    ]
